# This is my first .yaml file
name: Alfaiz Mansoor

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  biodata:
    # This is github runner
    runs-on: ubuntu-latest
    env:
      name: Alfaiz Mansuri
      role: devops engineer
      experience: 0.6-year
      learning: github action
      
