# This is my first .yaml file
name: Alfaiz Mansoor

on:
  push:
    branches: [main]
  workflow_dispatch: 

jobs:
  role:
    runs_on: ubuntu-latest
    types:
      - stream: Devops Engineer
    steps:
      - name: job role
        run: echo "Devops Engineer"

  experience:
    runs_on: ubuntu-latest
    year: months
    steps:
      - name: years of experience
        run: echo "years of experience"

  learning:
    runs_on: ubuntu-latest
    boolean: yes 
    steps:
      - name: still learning
        run: echo "Learning devops:True"
