# My first yaml file
name: Alfaiz

on:
  push:
    branches: [main]

jobs:
  role: 
    runs-on: ubuntu-latest
    outputs:
        job_role: Devops Engineer
  
  experience: 
    runs-on: ubuntu-latest
    outputs:
      years: 0.6
      
  learning:
    runs-on: ubuntu-latest
    outputs:
      boolean: true
